### ISSUE TITLE
running on llama-2

### ISSUE THREAD

**Issue by icecoldt369** [MikeWangWZHL/Solo-Performance-Prompting#3]
Hi Mike!

This is amazing work - thanks for sharing. I'm a beginner when it comes to prompt engineering and LLMs, and am inspired by your project.
I'm looking to test the prompting techniques on LLama-2. Are there any tips and pointers on how to run this code, the files to make amendments with and possible dependencies that I should keep an eye on? Sorry in advance if its already mentioned in the readme.md file

**Comment by MikeWangWZHL** [comment]
Thanks for the question; We will update the paper after ARR anonymous period where we included new experiments on Llama-2; We will also share the code for running that soon; Thanks
